<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# **Hands-on Lab : Web Scraping**

Estimated time needed: **30 to 45** minutes

## Objectives

In this lab you will perform the following:

*   Extract information from a given web site
*   Write the scraped data into a csv file.

## Extract information from the given web site

You will extract the data from the below web site: <br>

In [2]:
#this url contains the data you need to scrape
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/datasets/Programming_Languages.html"

The data you need to scrape is the **name of the programming language** and **average annual salary**.<br> It is a good idea to open the url in your web broswer and study the contents of the web page before you start to scrape.

Import the required libraries

In [3]:
# Your code here
from bs4 import BeautifulSoup
import requests

Download the webpage at the url

In [4]:
#your code goes here
data = requests.get(url).text

Create a soup object

In [5]:
#your code goes here
soup = BeautifulSoup(data,"html5lib")

Scrape the `Language name` and `annual average salary`.

In [6]:
#your code goes here
table = soup.find('table')
for row in table.find_all('tr'):
    cols = row.find_all('td')
    Language = cols[1].getText()
    average_salary = cols[3].getText()
    print("{}--->{}".format(Language, average_salary))

Language--->Average Annual Salary
Python--->$114,383
Java--->$101,013
R--->$92,037
Javascript--->$110,981
Swift--->$130,801
C++--->$113,865
C#--->$88,726
PHP--->$84,727
SQL--->$84,793
Go--->$94,082

Save the scrapped data into a file named *popular-languages.csv*

In [27]:
# your code goes here
import pandas as pd
table_rows = table.find_all('tr')
l = []
for row in table.find_all('tr'):
    cols = row.find_all('td')
    language_name = cols[1].getText()
    average_salary = cols[3].getText()
    l.append({"Language Name":language_name,"Average Salary":average_salary})
df=pd.DataFrame(l, columns=["Language Name","Average Salary"])
df
df.to_csv("popular-languages.csv")
df=pd.read_csv("popular-languages.csv")
df

    Unnamed: 0 Language Name         Average Salary
0            0      Language  Average Annual Salary
1            1        Python               $114,383
2            2          Java               $101,013
3            3             R                $92,037
4            4    Javascript               $110,981
5            5         Swift               $130,801
6            6           C++               $113,865
7            7            C#                $88,726
8            8           PHP                $84,727
9            9           SQL                $84,793
10          10            Go                $94,082

In [28]:
df = df.drop('Unnamed: 0', 1)
df.set_index('Language Name', inplace = True)
df

/tmp/wsuser/ipykernel_154/3689850160.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df = df.drop('Unnamed: 0', 1)

                      Average Salary
Language Name
Language       Average Annual Salary
Python                      $114,383
Java                        $101,013
R                            $92,037
Javascript                  $110,981
Swift                       $130,801
C++                         $113,865
C#                           $88,726
PHP                          $84,727
SQL                          $84,793
Go                           $94,082

In [24]:
df.dtypes

Average Salary    object
dtype: object

ValueError: invalid literal for int() with base 10: 'Average Annual Salary'

In [16]:
df.plot(kind = 'bar', figsize = (10, 6))

TypeError: no numeric data to plot

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01).